name: do_list
description: "a functional to-do list application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.13
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/fonts/
    - lib/assets/checklist.png

  fonts:
    - family: SourceSans3
      fonts:
        - asset: lib/assets/fonts/SourceSans3-Regular.ttf

    - family: RobotoMono
      fonts:
        - asset: lib/assets/fonts/RobotoMono-Regular.ttf
          weight: 700

flutter_native_splash:
  color: "#FFFFFF"
  image: "lib/assets/checklist.png"
  android: true
  ios: true
